services:
  php:
    build: .
    container_name: php
    volumes:
      - "./src:/var/www/html"
    working_dir: /var/www/html
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "3535:80"
    volumes:
      - "./src:/var/www/html"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: reddcs
      POSTGRES_PASSWORD: reddcs
    ports:
      - "2004:5432"
    volumes:
      - pgtables:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:snapshot
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: reddcs@gmail.com
      PGADMIN_DEFAULT_PASSWORD: reddcs
    ports:
      - "5050:80"
    depends_on:
      - postgres

  puml:
    image: plantuml/plantuml-server:jetty
    container_name: puml
    restart: always
    ports:
      - "4040:8080"
    volumes:
      - "./uml:/var/www/html/uml"

volumes:
  pgtables:
